name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Get Elixir Configured
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.2 # Define the elixir version [required]
        otp-version: 22 # Define the OTP version [required]
    
    # Install Dependencies
    - name: Install Dependencies
      run: |
        cd gardien_os
        mix archive.install --force hex nerves_bootstrap
        mix deps.get
      env:
        SECRET_KEY_BASE: literally_anything

    # Runs Unit Tests
    - name: Unit
      run: |
        cd gardien_os
        mix test
      env:
        SECRET_KEY_BASE: literally_anything

    # Runs Static Code Analysis
    - name: Static
      run: |
        cd gardien_os
        mix credo
      env:
        SECRET_KEY_BASE: literally_anything
        
